version: '3.8'

services:
  backend:
    volumes:
      - ./docker_files/gems/devise_ldap_authenticatable_forked_20190712:/usr/local/ngseq/gems/devise_ldap_authenticatable_forked_20190712:ro
      - ./docker_files/FGCZ_CA_2019.crt:/usr/local/share/ca-certificates/FGCZ_CA_2019.crt:ro
    environment:
      - ENABLE_LDAP=${ENABLE_LDAP:-1}
    command: >
      bash -c "update-ca-certificates || true && git config --global --add safe.directory /usr/local/ngseq/gems/devise_ldap_authenticatable_forked_20190712 && rm -f tmp/pids/server.pid && \
               if [ \"${ENABLE_LDAP}\" = \"1\" ]; then bundle install --with ldap; else bundle install; fi && \
               bundle exec rails db:migrate && \
               bundle exec rails server -b 0.0.0.0"




