version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
      args:
        - ENABLE_LDAP=${ENABLE_LDAP:-0}
    ports:
      - "${BACKEND_PORT:-4050}:80"
    environment:
      - RAILS_ENV=production
      - RAILS_MASTER_KEY=${RAILS_MASTER_KEY}
      - MYSQL_HOST=db
      - MYSQL_USER=${MYSQL_USER:-root}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD:-password}
      - MYSQL_DATABASE=${MYSQL_DATABASE:-sushi_app_production}
      # LDAP Configuration (bfabric)
      - LDAP_HOST=${LDAP_HOST:-fgcz-bfabric-ldap}
      - LDAP_PORT=${LDAP_PORT:-636}
      - LDAP_ATTRIBUTE=${LDAP_ATTRIBUTE:-cn}
      - LDAP_BASE=${LDAP_BASE:-dc=bfabric,dc=org}
      - LDAP_SSL=${LDAP_SSL:-true}
      - LDAP_SSL_VERIFY=${LDAP_SSL_VERIFY:-true}
    depends_on:
      - db
    volumes:
      - backend_storage:/rails/storage

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "${FRONTEND_PORT:-4051}:3000"
    environment:
      - NODE_ENV=production
    depends_on:
      - backend

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD:-password}
      MYSQL_DATABASE: ${MYSQL_DATABASE:-sushi_app_production}
      MYSQL_USER: ${MYSQL_USER:-sushi_user}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-password}
    volumes:
      - mysql_data:/var/lib/mysql
    restart: unless-stopped
    command: --default-authentication-plugin=mysql_native_password

volumes:
  backend_storage:
  mysql_data:

