version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
      args:
        - ENABLE_LDAP=${ENABLE_LDAP:-0}
    platform: linux/amd64
    ports:
      - "${BACKEND_PORT:-4050}:3000"
    volumes:
      - ./backend:/rails
      - bundle_cache:/usr/local/bundle
    environment:
      - RAILS_ENV=development
      - RAILS_SERVE_STATIC_FILES=true
      # LDAP Configuration (bfabric)
      - LDAP_HOST=${LDAP_HOST:-fgcz-bfabric-ldap}
      - LDAP_PORT=${LDAP_PORT:-636}
      - LDAP_ATTRIBUTE=${LDAP_ATTRIBUTE:-cn}
      - LDAP_BASE=${LDAP_BASE:-dc=bfabric,dc=org}
      - LDAP_SSL=${LDAP_SSL:-true}
      - LDAP_SSL_VERIFY=${LDAP_SSL_VERIFY:-true}
    command: >
      bash -c "rm -f tmp/pids/server.pid && \
               bundle check || BUNDLE_WITHOUT=ldap bundle install && \
               bundle exec rails db:migrate && \
               bundle exec rails server -b 0.0.0.0"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    platform: linux/amd64
    user: root
    ports:
      - "${FRONTEND_PORT:-4051}:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - /app/.next
    environment:
      - NODE_ENV=development
      - NEXT_PUBLIC_API_URL=http://${DEV_HOST:-localhost}:${BACKEND_PORT:-4050}
      - NEXT_PUBLIC_API_PORT=${BACKEND_PORT:-4050}
    depends_on:
      - backend
    command: ["npm", "run", "dev", "--", "--hostname", "0.0.0.0"]

volumes:
  bundle_cache:

